from app.db.database import (
    AsyncSessionLocal,
    AsyncTask,
    Base,
    ChatSession,
    CourseSpace,
    CustomPersona,
    Document,
    DocumentChunk,
    Message,
    Note,
    Quiz,
    QuizResult,
    Tag,
    User,
    UserLLMConfig,
    engine,
    ensure_current_schema,
    get_db,
    init_db,
    note_tags,
)
from app.db.migrations import get_current_revision, run_migrations, stamp_head
