"""initial_schema

Revision ID: f26617cd474b
Revises:
Create Date: 2026-06-21 14:58:49.464928

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f26617cd474b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
