/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/common/AppSidebar.vue')['default']
    ChatHistoryPanel: typeof import('./components/chat/ChatHistoryPanel.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    ClassroomBridgeDialog: typeof import('./components/integrations/ClassroomBridgeDialog.vue')['default']
    ConfirmDialog: typeof import('./components/common/ConfirmDialog.vue')['default']
    CopilotBotAvatar: typeof import('./components/CopilotBotAvatar.vue')['default']
    CourseCard: typeof import('./components/CourseCard.vue')['default']
    DocumentPicker: typeof import('./components/common/DocumentPicker.vue')['default']
    ElButton: typeof import('element-plus/es/components/button/index.mjs')['ElButton']
    ElCard: typeof import('element-plus/es/components/card/index.mjs')['ElCard']
    ElDialog: typeof import('element-plus/es/components/dialog/index.mjs')['ElDialog']
    ElDropdown: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es/components/dropdown/index.mjs')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es/components/form/index.mjs')['ElForm']
    ElFormItem: typeof import('element-plus/es/components/form/index.mjs')['ElFormItem']
    ElIcon: typeof import('element-plus/es/components/icon/index.mjs')['ElIcon']
    ElInput: typeof import('element-plus/es/components/input/index.mjs')['ElInput']
    ElInputNumber: typeof import('element-plus/es/components/input-number/index.mjs')['ElInputNumber']
    ElMenu: typeof import('element-plus/es/components/menu/index.mjs')['ElMenu']
    ElMenuItem: typeof import('element-plus/es/components/menu/index.mjs')['ElMenuItem']
    ElOption: typeof import('element-plus/es/components/select/index.mjs')['ElOption']
    ElOptionGroup: typeof import('element-plus/es/components/select/index.mjs')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es/components/pagination/index.mjs')['ElPagination']
    ElProgress: typeof import('element-plus/es/components/progress/index.mjs')['ElProgress']
    ElRadioButton: typeof import('element-plus/es/components/radio/index.mjs')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es/components/radio/index.mjs')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es/components/select/index.mjs')['ElSelect']
    ElSlider: typeof import('element-plus/es/components/slider/index.mjs')['ElSlider']
    ElSwitch: typeof import('element-plus/es/components/switch/index.mjs')['ElSwitch']
    ElTabPane: typeof import('element-plus/es/components/tabs/index.mjs')['ElTabPane']
    ElTabs: typeof import('element-plus/es/components/tabs/index.mjs')['ElTabs']
    ElTag: typeof import('element-plus/es/components/tag/index.mjs')['ElTag']
    ElTooltip: typeof import('element-plus/es/components/tooltip/index.mjs')['ElTooltip']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    NoteCard: typeof import('./components/NoteCard.vue')['default']
    NoteEditor: typeof import('./components/NoteEditor.vue')['default']
    OpenMAICLinkCard: typeof import('./components/integrations/OpenMAICLinkCard.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonList: typeof import('./components/common/SkeletonList.vue')['default']
    TaskPanel: typeof import('./components/TaskPanel.vue')['default']
    TransformDialog: typeof import('./components/TransformDialog.vue')['default']
    TTSPlayer: typeof import('./components/TTSPlayer.vue')['default']
    UrlImportDialog: typeof import('./components/UrlImportDialog.vue')['default']
  }
}
