/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/common/AppSidebar.vue')['default']
    ChatHistoryPanel: typeof import('./components/chat/ChatHistoryPanel.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    CourseCard: typeof import('./components/CourseCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    NoteCard: typeof import('./components/NoteCard.vue')['default']
    NoteEditor: typeof import('./components/NoteEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskPanel: typeof import('./components/TaskPanel.vue')['default']
    TransformDialog: typeof import('./components/TransformDialog.vue')['default']
    TTSPlayer: typeof import('./components/TTSPlayer.vue')['default']
    UrlImportDialog: typeof import('./components/UrlImportDialog.vue')['default']
  }
}
