from app.api.analysis import router as analysis_router
from app.api.auth import router as auth_router
from app.api.chat import router as chat_router
from app.api.classroom_api import router as classroom_router
from app.api.config import router as config_router
from app.api.courses import router as courses_router
from app.api.document import router as document_router
from app.api.metrics import router as metrics_router
from app.api.notes import router as notes_router
from app.api.quiz import router as quiz_router
from app.api.tasks import router as tasks_router
from app.api.transform import router as transform_router
from app.api.tts import router as tts_router
